#spring.mvc.static-path-pattern: /image/**
spring:
  mvc:
    static-path-pattern: /image/**
  resources:
    static-locations: file:F:/Documents/Works@cskaoyan/09 Project3/qr
dubbo:
  application:
    name: gateway
    owner: ciggar
  registry:
    address: zookeeper://127.0.0.1:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://127.0.0.1:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.cskaoyan.gateway
captchaFlag : false
